name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typing_extensions
          pip install -e ".[dev]"
      - name: Run tests with coverage
        run: |
          pytest --cov=safer_yaml --cov-fail-under=100
